version: '3.7'

services:
  pirate-kratos-migrate:
    image: oryd/kratos:v0.10.1
    environment:
      - DSN=postgres://super:super@postgres-db:5432/memberportdb?sslmode=disable&max_conns=20&max_idle_conns=4
      - SQA_OPT_OUT=true
    volumes:
      -
        type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./ory-config/kratos
        target: /etc/pirate-config
    command:
      -c /etc/pirate-config/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: memberportdb
      POSTGRES_USER: super
      POSTGRES_PASSWORD: super
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - intranet

  memberport:
    image: memberport:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pirate-kratos
      - rabbitmq
    ports:
      - "8888:8888"
    volumes:
      -
        type: bind
        source: ./config
        target: /app/config
      -
        type: bind
        source: ./app
        target: /app/app
      -
        type: bind
        source: ./templates
        target: /app/templates
      -
        type: bind
        source: ./static
        target: /app/static
    restart: on-failure
    networks:
      - intranet

  worker:
    image: memberport:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      -
        type: bind
        source: ./config
        target: /app/config
      -
        type: bind
        source: ./app
        target: /app/app
    command: celery -A app.tasks worker --loglevel=INFO
    depends_on:
      - rabbitmq
    networks:
      - intranet

  beat:
    image: memberport:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      -
        type: bind
        source: ./config
        target: /app/config
      -
        type: bind
        source: ./app
        target: /app/app
    command: celery -A app.tasks beat --loglevel=INFO
    depends_on:
      - rabbitmq
    networks:
      - intranet

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      -
        type: volume
        source: rabbitmq
        target: /var/lib/rabbitmq
        read_only: false
      -
        type: bind
        source: ./rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
    ports:
      - "4369:4369"
      - "5672:5672"
      - "8080:15672"
    networks:
      - intranet

  pirate-kratos:
    depends_on:
      - pirate-kratos-migrate
    image: oryd/kratos:v0.10.1
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://super:super@postgres-db:5432/memberportdb?sslmode=disable&max_conns=20&max_idle_conns=4
      - SQA_OPT_OUT=true
    command:
      serve -c /etc/pirate-config/kratos.yml --dev --watch-courier
    volumes:
      -
        type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./ory-config/kratos
        target: /etc/pirate-config
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
  intranet:

volumes:
  rabbitmq:
  kratos-sqlite:
  postgres:
